import { describe, expect, it } from "vitest";
import {
  analyzeTheme,
  editorLinks,
  isThemeAccessError,
  ourBlock,
  parseThemeJson,
  sortThemes,
  themeLabel,
  themeNumericId,
  type ThemeFile,
} from "./themes";

const type = (handle: string, app = "fitfinder") =>
  `shopify://apps/${app}/blocks/${handle}/0f6e8d5a-1111-2222-3333-444455556666`;

const settingsData = (blocks: Record<string, unknown>, asPreset = false) => ({
  filename: "config/settings_data.json",
  content:
    "/*\n * Generated by Shopify\n */\n" +
    JSON.stringify(
      asPreset
        ? { current: "Default", presets: { Default: { blocks } } }
        : { current: { blocks } },
    ),
});

const template = (
  name: string,
  sections: Record<string, unknown>,
): ThemeFile => ({
  filename: name,
  content: JSON.stringify({ sections, order: Object.keys(sections) }),
});

describe("ourBlock", () => {
  it("knows our handles and nothing else", () => {
    expect(ourBlock(type("fitfinder-search"))).toBe("search");
    expect(ourBlock(type("fitfinder-embed", "fitfinder-2"))).toBe("embed");
    expect(ourBlock(type("search", "other-app"))).toBeNull();
    expect(ourBlock(type("app-embed", "other-app"))).toBeNull();
    expect(ourBlock("shopify://apps/x/blocks/fitfinder-search")).toBeNull();
    expect(ourBlock(42)).toBeNull();
  });
});

describe("parseThemeJson", () => {
  it("drops a leading comment and survives bad JSON", () => {
    expect(parseThemeJson('/* hi */ {"a":1}')).toEqual({ a: 1 });
    expect(parseThemeJson("{nope")).toBeNull();
  });
});

describe("analyzeTheme", () => {
  it("reads the embed state from settings_data (enabled, disabled, never enabled)", () => {
    const on = { "1": { type: type("fitfinder-embed"), disabled: false } };
    const off = { "1": { type: type("fitfinder-embed"), disabled: true } };
    const other = { "1": { type: type("app-embed", "chat"), disabled: false } };
    expect(analyzeTheme([settingsData(on)]).embedOn).toBe(true);
    expect(analyzeTheme([settingsData(off)]).embedOn).toBe(false);
    expect(analyzeTheme([settingsData(other)]).embedOn).toBe(false);
    expect(analyzeTheme([]).embedOn).toBe(false);
  });

  it("follows a preset name in `current`", () => {
    const on = { x: { type: type("fitfinder-embed"), disabled: false } };
    expect(analyzeTheme([settingsData(on, true)]).embedOn).toBe(true);
  });

  it("finds blocks in templates (nested too) and remembers the template", () => {
    const status = analyzeTheme([
      template("templates/index.json", {
        apps: {
          type: "apps",
          blocks: { b1: { type: type("fitfinder-search") } },
        },
      }),
      template("templates/product.alt.json", {
        main: {
          type: "main-product",
          blocks: {
            group: {
              type: "group",
              blocks: { b2: { type: type("fitfinder-fits-badge") } },
            },
          },
        },
      }),
    ]);
    expect(status.blocks).toEqual({ search: "index", badge: "product.alt" });
  });

  it("ignores disabled blocks, disabled sections and other apps' blocks", () => {
    const status = analyzeTheme([
      template("templates/product.json", {
        main: {
          type: "main-product",
          blocks: {
            b1: { type: type("fitfinder-fits-badge"), disabled: true },
            b2: { type: type("search", "reviews") },
          },
        },
        hidden: {
          type: "apps",
          disabled: true,
          blocks: { b3: { type: type("fitfinder-fitment-table") } },
        },
      }),
    ]);
    expect(status.blocks).toEqual({});
  });

  it("prefers a template over a section group for View in editor", () => {
    const group = template("sections/header-group.json", {
      apps: { type: "apps", blocks: { b: { type: type("fitfinder-search") } } },
    });
    const index = template("templates/index.json", {
      apps: { type: "apps", blocks: { b: { type: type("fitfinder-search") } } },
    });
    expect(analyzeTheme([group, index]).blocks.search).toBe("index");
    expect(analyzeTheme([group]).blocks.search).toBe("");
  });

  it("finds the [fitfinder-table] code in product templates only", () => {
    const tab = {
      main: {
        type: "main-product",
        blocks: {
          t: {
            type: "collapsible_tab",
            settings: { content: "<p>[fitfinder-table]</p>" },
          },
        },
      },
    };
    expect(
      analyzeTheme([template("templates/product.json", tab)]).tableCodeFound,
    ).toBe(true);
    expect(
      analyzeTheme([template("templates/page.json", tab)]).tableCodeFound,
    ).toBe(false);
  });
});

describe("themes and links", () => {
  it("labels and sorts themes, live first", () => {
    const themes = sortThemes([
      { id: "3", name: "Zed", role: "UNPUBLISHED" },
      { id: "2", name: "Dev", role: "DEVELOPMENT" },
      { id: "1", name: "Dawn", role: "MAIN" },
      { id: "4", name: "Alpha", role: "UNPUBLISHED" },
    ]);
    expect(themes.map((t) => t.id)).toEqual(["1", "4", "3", "2"]);
    expect(themeLabel(themes[0])).toBe("Dawn (live theme)");
    expect(themeLabel(themes[1])).toBe("Alpha (draft)");
    expect(themeNumericId("gid://shopify/OnlineStoreTheme/123")).toBe("123");
  });

  it("builds the documented theme editor deep links", () => {
    const l = editorLinks("demo.myshopify.com", "123", "KEY");
    const base = "https://demo.myshopify.com/admin/themes/123/editor";
    expect(l.editor).toBe(base);
    expect(l.embedOn).toBe(
      `${base}?context=apps&activateAppId=KEY%2Ffitfinder-embed`,
    );
    expect(l.embedPanel).toBe(`${base}?context=apps`);
    expect(l.add.search).toBe(
      `${base}?template=index&addAppBlockId=KEY%2Ffitfinder-search&target=newAppsSection`,
    );
    expect(l.add.badge).toBe(
      `${base}?template=product&addAppBlockId=KEY%2Ffitfinder-fits-badge&target=mainSection`,
    );
    expect(l.add.table).toContain(
      "addAppBlockId=KEY%2Ffitfinder-fitment-table",
    );
    expect(l.view("product.alt")).toBe(`${base}?template=product.alt`);
    expect(l.view("")).toBe(base);
  });
});

describe("isThemeAccessError", () => {
  it("finds ACCESS_DENIED in a GraphqlQueryError body", () => {
    const error = Object.assign(
      new Error(
        "GraphQL Client: An error occurred while fetching from the API. Review 'graphQLErrors' for details.",
      ),
      {
        body: {
          errors: {
            graphQLErrors: [
              {
                message: "Access denied for themes field.",
                extensions: { code: "ACCESS_DENIED" },
              },
            ],
          },
        },
      },
    );
    expect(isThemeAccessError(error)).toBe(true);
  });

  it("finds it in gqlData's own error message", () => {
    expect(
      isThemeAccessError(
        new Error(
          'Admin API error: [{"message":"Access denied for themes field. Required access: `read_themes` access scope.","extensions":{"code":"ACCESS_DENIED"}}]',
        ),
      ),
    ).toBe(true);
  });

  it("is false for other failures", () => {
    expect(isThemeAccessError(new Error("fetch failed"))).toBe(false);
    expect(isThemeAccessError(null)).toBe(false);
  });
});
